name = "cf-ai-webpage-chat"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "webpage-chat-db"
database_id =  "ff2ec742-2417-4528-9ed0-b9ab85e8c5be"

[[vectorize]]
binding = "VECTORIZE"
index_name = "webpage-embeddings"
remote = true

[ai]
binding = "AI"
remote= true

[[workflows]]
binding = "INGEST_WORKFLOW"
name = "ingest-workflow"
class_name = "IngestWorkflow"

[assets]
directory = "../frontend"
binding = "ASSETS"
